#!/usr/bin/env bash
set -euo pipefail

if [ -z "${1-}" ]; then
    echo "Usage: $0 <PROJECT_NAME>"
    exit 1
fi

PROJECT_NAME="$1"

echo "Step 1: Generating project..."
source ./generate_project.sh
generate_project "$PROJECT_NAME"

echo "Step 2: Remove the .dockerignore generated by Quarkus..."
rm "$PROJECT_NAME/.dockerignore"

echo "Step 3: Moving project files up one level..."
source ./move_files.sh
move_project_files "$PROJECT_NAME"

echo "Step 4: Replacing project name placeholders..."
source ./rename_project.sh
rename_project "$PROJECT_NAME"

echo "Step 5: Merge our README.md with their README.md"
source ./text_utils.sh
partial_content=$(cat partialREADME.md)
text_utils::replace_in_file "README.md" '#\$PROJECT_NAME' "$partial_content"

echo "Step 6: Cleaning up temporary scripts..."
rm -f generate_project.sh move_files.sh rename_project.sh create.sh

echo "Project setup complete!"
