name: {PROJECT_NAME}

services:
  symfony-env:
    container_name: ${COMPOSE_PROJECT_NAME}-symfony-env
    build: .
    volumes:
      - ./:/var/www/symfony
    ports:
      - ${DOCKER_PORT:-8000}:8000

    command: tail -f /dev/null
