name: {PROJECT_NAME}

services:
  java-env:
    container_name: ${COMPOSE_PROJECT_NAME}-java-env
    build:
      context: .
      target: dev
    image: ${COMPOSE_PROJECT_NAME}-java-env:latest
    volumes:
      - .:/workspace
      - {PROJECT_NAME}_maven_cache:/root/.m2
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  {PROJECT_NAME}_maven_cache: