name: foobar

services:
  java-env:
    container_name: ${COMPOSE_PROJECT_NAME}-java-env
    build:
      context: .
      target: dev
    image: ${COMPOSE_PROJECT_NAME}-java-env:latest
    volumes:
      - .:/workspace
      - foobar_maven_cache:/root/.m2
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  foobar_maven_cache: