#!/usr/bin/env bash
set -euo pipefail

# ======== MANUAL CONFIGURATION ========
SERVICE_NAME="python-env"
ENTRYPOINT=$1
shift
ARGS=("$@")
# ======================================

CONTAINER_ID=

start_docker_compose() {
    echo "Starting Docker Compose..."
    docker compose up -d
    echo ""

    CONTAINER_ID=$(docker compose ps -q "$SERVICE_NAME")
    if [ -z "$CONTAINER_ID" ]; then
        echo "Error: Could not find the container ID for the '$SERVICE_NAME' service." >&2
        exit 1
    fi
}

kill_docker_container() {
    docker kill "$CONTAINER_ID" >/dev/null 2>&1
}

install_packages_in_container() {
    docker exec "$CONTAINER_ID" ./make install-package
    echo ""
}

run_binary_in_container() {
    echo "Running $ENTRYPOINT in the Docker container with args: ${ARGS[*]}"
    docker exec "$CONTAINER_ID" ./make run "$ENTRYPOINT" "${ARGS[@]}"
    echo ""
}

# ======== EXECUTION FLOW ========
start_docker_compose
install_packages_in_container
run_binary_in_container
kill_docker_container
